// Automatically generated by astro-icon
// 6339060a2f9d69e8b84a4b7dc1714c2937d6db46d28442485b0129d1ad20d45b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arc"
		| "chatgpt"
		| "figma"
		| "notion"
		| "obsidian"
		| "vscode";
}